preset: psr2

linting: true

enabled:
  - align_double_arrow
  - align_equals
  - blankline_after_open_tag
  - concat_with_spaces
  - double_arrow_multiline_whitespaces
  - duplicate_semicolon
  - empty_return
  - extra_empty_lines
  - function_typehint_space
  - logical_not_operators_with_spaces
  - method_separation
  - multiline_array_trailing_comma
  - multiline_spaces_before_semicolon
  - newline_after_open_tag
  - no_empty_lines_after_phpdocs
  - operators_spaces
  - ordered_use
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - php_unit_construct
  - remove_leading_slash_use
  - self_accessor
  - short_array_syntax
  - short_echo_tag
  - single_array_no_trailing_comma
  - spaces_cast
  - standardize_not_equal
  - ternary_spaces
  - unary_operators_spaces
  - unused_use
  - whitespacy_lines

finder:
  path:
    - "src/"